### ISSUE TITLE
`0.4.0` agent distro fails to load

### ISSUE THREAD

**Issue by bixu** [honeycombio/honeycomb-opentelemetry-java#127]
**Versions**

- Java: 11
- Honeycomb OpenTelemetry Distribution: 0.4.0

Create a Dockerfile with this base image, `COPY` and `CMD`:

```shell
FROM adoptopenjdk/openjdk11:alpine-jre

COPY honeycomb-opentelemetry-javaagent-0.4.0-all.jar  honeycomb-opentelemetry-javaagent-0.4.0-all.jar 

CMD java \
    -javaagent:honeycomb-opentelemetry-javaagent-0.4.0-all.jar  \
    -jar yourApp.jar
```

```shell
Exception in thread "main" java.lang.reflect.InvocationTargetException
FATAL ERROR in native method: processing of -javaagent failed, processJavaStart failed
      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
      at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
      at java.base/java.lang.reflect.Method.invoke(Unknown Source)
      at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(Unknown Source)
      at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(Unknown Source)
Caused by: java.lang.NoSuchMethodError: 'boolean io.honeycomb.opentelemetry.EnvironmentConfiguration.isPresent(java.lang.String)'
      at io.honeycomb.opentelemetry.HoneycombAgent.configureEnvironment(HoneycombAgent.java:32)
      at io.honeycomb.opentelemetry.HoneycombAgent.premain(HoneycombAgent.java:17)
      ... 6 more
*** java.lang.instrument ASSERTION FAILED ***: "result" with message agent load/premain call failed at ./src/java.instrument/share/native/libinstrument/JPLISAgent.c line: 422
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f07e40bc93b, pid=1, tid=11
#
# JRE version: OpenJDK Runtime Environment Temurin-11.0.12+7 (11.0.12+7) (build 11.0.12+7)
# Java VM: OpenJDK 64-Bit Server VM Temurin-11.0.12+7 (11.0.12+7, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# C  [libc.so.6+0x2693b]  abort+0x1ed
#
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# //hs_err_pid1.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
#
exited with code 127
```

**Comment by MikeGoldsmith** [comment]
Thanks for the bug report @bixu - we'll add it to our backlog for review 👍🏻

**Comment by vreynolds** [comment]
Hey @bixu , trying to reproduce this error and coming up short 😞 Using the exact Dockerfile, and the agent JAR from release 0.4.0.

I _suspect_ that the `EnvironmentConfiguration` was somehow cached from a previous version (before `isPresent` was added) in the class loader, but I don't see how that would be the case for a new image build...

Is there anything else you could think of that could be affecting your environment? Can you confirm that the agent JAR you have has the `EnvironmentConfiguration.class` with an `isPresent` symbol?

**Comment by vreynolds** [comment]
Some additional things that would be helpful:
- how do you source the agent JAR?
- were you upgrading from 0.3.0 to 0.4.0? (thinking of what could be cached in that process)

**Comment by bixu** [comment]
@vreynolds, we were indeed updating.

We source the agent JAR like:

```shell
# Dockerfile stuff

ENV OTEL_AGENT_VERSION="0.4.0"

# more Dockerfile stuff

RUN curl --silent --location \
    "https://github.com/honeycombio/honeycomb-opentelemetry-java/releases/download/v${OTEL_AGENT_VERSION}/honeycomb-opentelemetry-javaagent-${OTEL_AGENT_VERSION}-all.jar" > honeycomb-opentelemetry-javaagent.jar \
        && sha256sum honeycomb-opentelemetry-javaagent.jar | cut -d' ' -f1 | grep '020786a2813ad7c274d139bb536ac88114d7b1abf147c660694bdc3dbcf20458' \
        && cp honeycomb-opentelemetry-javaagent.jar ${APP_BASE}/${APP_NAME}/honeycomb-opentelemetry-javaagent.jar
```

**Comment by vreynolds** [comment]
Thanks for the example! Sadly, still no dice 😢 Here's the Dockerfile we're using:

```
FROM adoptopenjdk/openjdk11:alpine-jre

ENV OTEL_AGENT_VERSION="0.4.0"
ENV HONEYCOMB_AGENT_SHA="77716f43aa4539e3118e797577351c170939d6e3783347cd04454af64e4556be"

RUN apk --no-cache add curl

RUN mkdir -p /app-base/app-name

RUN curl --silent --location \
    "https://github.com/honeycombio/honeycomb-opentelemetry-java/releases/download/v${OTEL_AGENT_VERSION}/honeycomb-opentelemetry-javaagent-${OTEL_AGENT_VERSION}-all.jar" > honeycomb-opentelemetry-javaagent.jar \
        && sha256sum honeycomb-opentelemetry-javaagent.jar | cut -d' ' -f1 | grep $HONEYCOMB_AGENT_SHA \
        && cp honeycomb-opentelemetry-javaagent.jar /app-base/app-name/honeycomb-opentelemetry-javaagent.jar

COPY build/libs/name-java-0.0.1-SNAPSHOT.jar  /app-base/app-name/name-java-0.0.1-SNAPSHOT.jar

WORKDIR /app-base/app-name

CMD java \
    -javaagent:honeycomb-opentelemetry-javaagent.jar  \
    -jar name-java-0.0.1-SNAPSHOT.jar
```

- Is it the same SHA?
- Is there anything else that could possibly affect the jar or jvm?
