### ISSUE TITLE
Agent failed to run on Java 17

### ISSUE THREAD

**Issue by wdjunaidi** [honeycombio/honeycomb-opentelemetry-java#398]
**Versions**

- Java: 17
- Honeycomb OpenTelemetry Distribution: 0.10.0, 1.3.0, 1.4.0, 1.4.1, 1.4.2

**Steps to reproduce**

1. Running Spring Boot 2.7 in Docker Container on AWS ECS
    - Docker image: amazoncoretto:17-alpine, openjdk:17-jdk-alpine
2. Docker execution:
```
# Download datadog agent
RUN wget -O dd-java-agent.jar 'https://dtdg.co/latest-java-tracer'
# Download honeycomb agent
RUN wget -O honeycomb-javaagent.jar 'https://github.com/honeycombio/honeycomb-opentelemetry-java/releases/download/v0.10.0/honeycomb-opentelemetry-javaagent-0.10.0.jar'

ENTRYPOINT java -javaagent:dd-java-agent.jar -javaagent:honeycomb-javaagent.jar -jar /app.jar
``` 
3. On application starting, honeycomb agent failed to start with the following log:
```
[dd.trace 2023-02-21 08:45:58:633 +1300] [main] INFO com.datadog.appsec.AppSecSystem - AppSec is ENABLED_INACTIVE with powerwaf(libddwaf: 1.6.2) no rules loaded
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
ERROR io.opentelemetry.javaagent.OpenTelemetryAgent
java.lang.ClassCircularityError: io/opentelemetry/javaagent/bootstrap/AgentClassLoader
at io.opentelemetry.javaagent.bootstrap.AgentClassLoader$BootstrapClassLoaderProxy.getResource(AgentClassLoader.java:363)
at io.opentelemetry.javaagent.bootstrap.AgentClassLoader.getResource(AgentClassLoader.java:266)
at java.base/java.net.URLClassLoader.getResourceAsStream(URLClassLoader.java:284)
at io.opentelemetry.javaagent.slf4j.impl.SimpleLoggerConfiguration$1.run(SimpleLoggerConfiguration.java:104)
at io.opentelemetry.javaagent.slf4j.impl.SimpleLoggerConfiguration$1.run(SimpleLoggerConfiguration.java:100)
at java.base/java.security.AccessController.doPrivileged(AccessController.java:312)
at io.opentelemetry.javaagent.slf4j.impl.SimpleLoggerConfiguration.loadProperties(SimpleLoggerConfiguration.java:100)
at io.opentelemetry.javaagent.slf4j.impl.SimpleLoggerConfiguration.init(SimpleLoggerConfiguration.java:70)
at io.opentelemetry.javaagent.slf4j.impl.SimpleLogger.init(SimpleLogger.java:173)
at io.opentelemetry.javaagent.slf4j.impl.SimpleLogger.lazyInit(SimpleLogger.java:167)
at io.opentelemetry.javaagent.slf4j.impl.SimpleLoggerFactory.<init>(SimpleLoggerFactory.java:45)
at io.opentelemetry.javaagent.slf4j.impl.StaticLoggerBinder.<init>(StaticLoggerBinder.java:71)
at io.opentelemetry.javaagent.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:44)
at io.opentelemetry.javaagent.slf4j.LoggerFactory.bind(LoggerFactory.java:150)
at io.opentelemetry.javaagent.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
at io.opentelemetry.javaagent.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:417)
at io.opentelemetry.javaagent.slf4j.LoggerFactory.getLogger(LoggerFactory.java:362)
at io.opentelemetry.javaagent.slf4j.LoggerFactory.getLogger(LoggerFactory.java:388)
at io.opentelemetry.javaagent.tooling.AgentInstaller.<clinit>(AgentInstaller.java:76)
at io.opentelemetry.javaagent.tooling.AgentStarterImpl.start(AgentStarterImpl.java:65)
at io.opentelemetry.javaagent.bootstrap.AgentInitializer.initialize(AgentInitializer.java:35)
at io.opentelemetry.javaagent.OpenTelemetryAgent.startAgent(OpenTelemetryAgent.java:55)
at io.opentelemetry.javaagent.OpenTelemetryAgent.premain(OpenTelemetryAgent.java:44)
at io.honeycomb.opentelemetry.HoneycombAgent.premain(HoneycombAgent.java:16)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:490)
at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:502)
```
**Additional context**
We have application running on Java 11 with `eclipse-temurin:11-jre-alpine`, the agent is running fine with the following log:
```
[dd.trace 2023-02-21 08:45:44:484 +1300] [main] INFO com.datadog.appsec.AppSecSystem - AppSec is ENABLED_INACTIVE with powerwaf(libddwaf: 1.5.1) no rules loaded
[otel.javaagent 2023-02-21 08:45:46:776 +1300] [main] INFO io.opentelemetry.javaagent.tooling.VersionLogger - opentelemetry-javaagent - version: honeycomb-0.10.0-otel-1.11.1
```

**Comment by MikeGoldsmith** [comment]
Hi @wdjunaidi 

v0.10.0 of the Honeycomb agent is quite old now and many fixes & improvments have been made both in the OpenTelemetry Agent & SDK and our wrappers.

The latest release is [v1.4.2](https://github.com/honeycombio/honeycomb-opentelemetry-java/releases/tag/v1.4.2) - please can you try that?

**Comment by JamieDanielson** [comment]
@wdjunaidi Could you try without the Datadog agent and see if you have the same issue? Also, it's not clear from your provided docker execution whether you used version 0.10.0 or if that's just a copy/paste example and you substituted other versions... but this should work with the latest version and Java17 so I'm curious if running both agents is causing the problem.

**Comment by wdjunaidi** [comment]
Hi,

As mentioned on the issue description, we've tried from 0.10.0, 1.3.0, 1.4.0, 1.4.2, all have the same issue.

However, the good news is we got it working by changing the order of execution of the java agent. So when we put honeycomb javaagent first before datadog agent, it works fine.

I'll close this issue as solved.
